### Verificación de las cuestiones

In [ ]:
# Revisando que todo esté en orden
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

print(f"pandas ready     {pd.__version__}")
print(f"matplotlib ready {plt.matplotlib.__version__}")
print(f"seaborn ready    {sns.__version__}")
print(f"scikit-learn ready {sklearn.__version__}")
print("\nEso es todo")

### Cargar dataset

In [ ]:
# Carga del dataset de kaggle
df = pd.read_csv("../dataset/stackoverflow_combined.csv")

print(f"Dataset listo")
print(f"Filas: {df.shape[0]:,}")
print(f"Columnas: {df.shape[1]}")

Dataset listo
Filas: 95,636
Columnas: 34
El shape: (95636, 34)

### Revisión de filas

In [14]:
# Revisar las 10 primeras filas
df.head(10)

,question_id,title,body,tags,tag_count,programming_language,categories,creation_date,creation_year,creation_month,...,body_word_count,body_char_count,difficulty_score,quality_score,owner_reputation,owner_badge_count,first_response_time_seconds,first_response_time_hours,top_answer_score,top_answer_body_length
0,79810291,AttributeError: 'NoneType' object has no attri...,I am trying to develop a tool that agent (Code...,"python, artificial-intelligence, huggingface, ...",4,python,"bug, api, backend",2025-11-05 15:49:00,2025,11,...,36,190,0.200,0.70,345,0,NaN,NaN,0,0
1,79810195,"contextlib tries to change a ""frozen"" exception",I got a strange error in my pytest after some ...,"python, minio",2,python,"bug, testing",2025-11-05 14:23:06,2025,11,...,113,599,0.200,0.70,529,0,NaN,NaN,0,0
2,79810063,Tkinter window shrinks after embedding Matplot...,I'm building a multi-frame Tkinter app for a s...,"python, matplotlib, tkinter",3,python,"api, backend",2025-11-05 12:42:01,2025,11,...,143,812,0.201,0.70,21,0,NaN,NaN,0,0
3,79810057,"CatalystAppError: {'code': 'FATAL ERROR', 'mes...",I’m working on a chatbot project using the Zoh...,"python, zoho, zohocatalyst",3,python,bug,2025-11-05 12:36:07,2025,11,...,124,905,0.202,0.68,9,0,NaN,NaN,0,0
4,79810049,Sympy : Problem with simplifying a Sympy vecto...,I am creating my own coordinate system using t...,"python, sympy",2,python,bug,2025-11-05 12:28:43,2025,11,...,109,710,0.199,0.70,1620,0,NaN,NaN,0,0
5,79809980,Turn off Gemini's reasoning in DSPy,"In my DSPy project, I am using Gemini 2.5 Flas...","python, google-gemini, reasoning, dspy",4,python,NaN,2025-11-05 11:37:00,2025,11,...,45,239,0.201,0.90,324,0,1852.0,0.514444,2,78
6,79809939,The Pyrogram client does not recognize the id ...,Below are two scripts. The first one creates a...,"python, telegram, aiogram, pyrogram",4,python,bug,2025-11-05 10:56:42,2025,11,...,138,768,0.202,0.90,59,0,14587.0,4.051944,0,450
7,79809924,Python SSH automation. Child process communica...,I am trying to automate SSH authentication on ...,"python, ssh, automation, tty",4,python,"bug, security, backend",2025-11-05 10:36:06,2025,11,...,151,925,0.202,0.70,21,0,NaN,NaN,0,0
8,79809886,A wrapper route to simulate a FastAPI request,My goal is to have a special route which recei...,"python, fastapi, middleware, asgi",4,python,"api, backend",2025-11-05 10:04:13,2025,11,...,102,567,0.202,0.90,197,0,13600.0,3.777778,0,21
9,79809789,Panel: StaticText value update not appearing o...,I'm having an issue with the holoviz panel wid...,"python, holoviz-panel",2,python,how-to,2025-11-05 08:18:46,2025,11,...,161,1046,0.202,0.70,87,0,NaN,NaN,0,0

### Revision de columnas

In [8]:
df.columns

Index(['question_id', 'title', 'body', 'tags', 'tag_count',
       'programming_language', 'categories', 'creation_date', 'creation_year',
       'creation_month', 'creation_weekday', 'last_activity_date',
       'view_count', 'score', 'answer_count', 'comment_count',
       'favorite_count', 'is_answered', 'has_accepted_answer',
       'accepted_answer_score', 'has_code', 'code_block_count',
       'title_word_count', 'title_char_count', 'body_word_count',
       'body_char_count', 'difficulty_score', 'quality_score',
       'owner_reputation', 'owner_badge_count', 'first_response_time_seconds',
       'first_response_time_hours', 'top_answer_score',
       'top_answer_body_length'],
      dtype='str')

### Estructura del dataset

In [6]:
#Tipos de datos y valores nulos
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 95636 entries, 0 to 95635
Data columns (total 34 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   question_id                  95636 non-null  int64
 1   title                        95636 non-null  str
 2   body                         95614 non-null  str
 3   tags                         95636 non-null  str
 4   tag_count                    95636 non-null  int64
 5   programming_language         95636 non-null  str
 6   categories                   71744 non-null  str
 7   creation_date                95636 non-null  str
 8   creation_year                95636 non-null  int64
 9   creation_month               95636 non-null  int64
 10  creation_weekday             95636 non-null  int64
 11  last_activity_date           95636 non-null  str
 12  view_count                   95636 non-null  int64
 13  score                        95636 non-null  int64
 14  answer_count                 95636 non-null  int64
 15  comment_count                95636 non-null  int64
 16  favorite_count               95636 non-null  int64
 17  is_answered                  95636 non-null  bool
 18  has_accepted_answer          95636 non-null  bool
 19  accepted_answer_score        95636 non-null  int64
 20  has_code                     95636 non-null  bool
 21  code_block_count             95636 non-null  int64
 22  title_word_count             95636 non-null  int64
 23  title_char_count             95636 non-null  int64
 24  body_word_count              95636 non-null  int64
 25  body_char_count              95636 non-null  int64
 26  difficulty_score             95636 non-null  float64
 27  quality_score                95636 non-null  float64
 28  owner_reputation             95636 non-null  int64
 29  owner_badge_count            95636 non-null  int64
 30  first_response_time_seconds  66428 non-null  float64
 31  first_response_time_hours    66428 non-null  float64
 32  top_answer_score             95636 non-null  int64
 33  top_answer_body_length       95636 non-null  int64
dtypes: bool(3), float64(4), int64(20), str(7)
memory usage: 22.9 MB

### Estadistica general

In [ ]:
#Resumen estadistico
df.describe()

,question_id,tag_count,creation_year,creation_month,creation_weekday,view_count,score,answer_count,comment_count,favorite_count,...,body_word_count,body_char_count,difficulty_score,quality_score,owner_reputation,owner_badge_count,first_response_time_seconds,first_response_time_hours,top_answer_score,top_answer_body_length
count,9.563600e+04,95636.000000,95636.000000,95636.000000,95636.000000,95636.000000,95636.000000,95636.000000,95636.0,95636.0,...,95636.000000,95636.000000,95636.000000,95636.000000,9.563600e+04,95636.0,6.642800e+04,66428.000000,95636.000000,95636.000000
mean,7.835358e+07,3.282969,2024.175666,6.504810,2.664624,241.632471,0.710935,0.975292,0.0,0.0,...,116.469342,665.482297,0.205000,0.871328,2.910440e+03,0.0,4.704636e+05,130.684340,1.156113,372.934397
std,2.424297e+06,1.186866,1.038330,3.428266,1.856090,1963.430011,1.987928,0.887141,0.0,0.0,...,84.167591,520.869498,0.026876,0.129268,1.590858e+04,0.0,2.880631e+06,800.175215,2.536013,591.162679
min,6.481970e+07,1.000000,2020.000000,1.000000,0.000000,2.000000,-18.000000,0.000000,0.0,0.0,...,0.000000,0.000000,0.001000,0.300000,0.000000e+00,0.0,0.000000e+00,0.000000,-6.000000,0.000000
25%,7.860656e+07,2.000000,2024.000000,3.000000,1.000000,63.000000,0.000000,0.000000,0.0,0.0,...,62.000000,345.000000,0.201000,0.700000,1.900000e+01,0.0,2.252000e+03,0.625556,0.000000,0.000000
50%,7.929586e+07,3.000000,2024.000000,7.000000,3.000000,97.000000,0.000000,1.000000,0.0,0.0,...,96.000000,537.000000,0.203000,0.900000,9.300000e+01,0.0,9.904500e+03,2.751250,0.000000,193.000000
75%,7.959418e+07,4.000000,2025.000000,10.000000,4.000000,175.000000,1.000000,1.000000,0.0,0.0,...,146.000000,834.000000,0.209000,1.000000,8.450000e+02,0.0,6.253975e+04,17.372153,2.000000,489.000000
max,7.982051e+07,5.000000,2025.000000,12.000000,6.000000,317919.000000,195.000000,16.000000,0.0,0.0,...,2733.000000,17924.000000,0.993000,1.000000,1.010847e+06,0.0,1.002907e+08,27858.523889,278.000000,21783.000000

### Revisar los lenguajes disponibles

In [ ]:
# Revisar cuales son los lenguajes que aparecen
print("Lenguajes del dataset:")
print(df["programming_language"].unique())
print(f"\nTotal: {df["programming_language"].nunique()} lenguajes")

Lenguajes del dataset:
<StringArray>
[    'python', 'javascript',       'html',       'java',         'c#',
        'php',        'c++',          'c',          'r',        'sql',
        'css',         'go', 'typescript',       'dart',      'shell',
       'bash', 'powershell',      'swift',       'ruby',     'kotlin',
      'scala',       'rust',    'haskell',     'matlab',       'perl']
Length: 25, dtype: str

Total: 25 lenguajes

### Verificación de fechas

In [29]:
# Revisar si en verdad va de 2020 a 2025
print(f"Fecha mas antigua: {df["creation_date"].min()}")
print(f"Fecha mas nueva: {df["creation_date"].max()}")

Fecha mas antigua: 2020-11-13 10:58:06
Fecha mas nueva: 2025-11-14 23:42:35